export const QUERY_HISTORY = {
  MAX_ENTRIES_PER_USER: 200,
  MAX_SQL_LENGTH: 100_000,
  MAX_DATABASE_USER_LENGTH: 30,
  MAX_SITE_NAME_LENGTH: 50,
  MAX_IMPORT_ITEMS: 1000,
  BODY_LIMIT: '10mb',
  TIMESTAMP_FORMAT: 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"',
} as const;
