-- Migration: scope CONNECTIONS uniqueness to (USER_ID, SITE) instead of SITE alone,
-- so different users can each name a connection the same thing.

ALTER TABLE CONNECTIONS MODIFY (USER_ID NUMBER NOT NULL);
ALTER TABLE CONNECTIONS DROP CONSTRAINT CONNECTIONS_PK;
ALTER TABLE CONNECTIONS ADD CONSTRAINT CONNECTIONS_PK PRIMARY KEY (USER_ID, SITE);
ALTER TABLE CONNECTIONS ADD CONSTRAINT FK_CONNECTIONS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);
