-- Migration: per-user UI preferences, stored separately from USERS.

CREATE TABLE USER_PREFERENCES (
  USER_ID                 NUMBER PRIMARY KEY,
  APPEARANCE              VARCHAR2(10) DEFAULT 'light' NOT NULL
                           CHECK (APPEARANCE IN ('light', 'dark')),
  ACCENT_COLOR            VARCHAR2(20) DEFAULT 'blue' NOT NULL,
  CONTENT_LAYOUT_MODE     VARCHAR2(10) DEFAULT 'list' NOT NULL
                           CHECK (CONTENT_LAYOUT_MODE IN ('grid', 'list')),
  FONT_SIZE               VARCHAR2(10) DEFAULT 'medium' NOT NULL
                           CHECK (FONT_SIZE IN ('small', 'medium', 'large')),
  ROWS_PER_PAGE           NUMBER DEFAULT 50 NOT NULL,
  CONFIRM_BEFORE_DELETE   CHAR(1) DEFAULT 'Y' NOT NULL CHECK (CONFIRM_BEFORE_DELETE IN ('Y', 'N')),
  USE_MONOSPACED_DATA     CHAR(1) DEFAULT 'N' NOT NULL CHECK (USE_MONOSPACED_DATA IN ('Y', 'N')),
  SHOW_ROW_SEPARATORS     CHAR(1) DEFAULT 'Y' NOT NULL CHECK (SHOW_ROW_SEPARATORS IN ('Y', 'N')),
  USE_BOLD_TEXT           CHAR(1) DEFAULT 'N' NOT NULL CHECK (USE_BOLD_TEXT IN ('Y', 'N')),
  UPDATED_AT              DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT FK_USER_PREFERENCES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
